# Generated by Django 3.0.4 on 2020-03-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.CharField(blank=True, max_length=120, null=True)),
                ('lon', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('org_type', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('is_dropoff_only', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True)),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.CharField(blank=True, max_length=120, null=True)),
                ('lon', models.CharField(blank=True, max_length=120, null=True)),
                ('point_of_contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_zero.User')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=120)),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_received', models.PositiveIntegerField(default=0)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_zero.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120, null=True)),
                ('item_type', models.CharField(max_length=120, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('donation_time', models.DateTimeField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_zero.Organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_zero.User')),
            ],
        ),
    ]
