# Generated by Django 3.0.4 on 2020-03-30 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('status', models.CharField(max_length=120)),
                ('item', models.CharField(max_length=120)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('city', models.CharField(max_length=120)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('delivery_type', models.CharField(max_length=120)),
                ('pickup_or_dropoff_times', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120)),
                ('org_type', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('is_dropoff', models.BooleanField()),
                ('is_pickup', models.BooleanField()),
                ('is_mail', models.BooleanField()),
                ('dropoff_instructions', models.TextField(blank=True, null=True)),
                ('pickup_instructions', models.TextField(blank=True, null=True)),
                ('mail_instructions', models.TextField(blank=True, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.CharField(blank=True, max_length=120, null=True)),
                ('lon', models.CharField(blank=True, max_length=120, null=True)),
                ('auth_user_id', models.CharField(max_length=120)),
                ('pickup_times', models.TextField(blank=True, null=True)),
                ('dropoff_times', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.CharField(blank=True, max_length=120, null=True)),
                ('lon', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HashToDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=120)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation', to='helper_zero.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=120)),
                ('item_type', models.CharField(max_length=120)),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_received', models.PositiveIntegerField()),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donation_requests', to='helper_zero.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='donation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='helper_zero.Organization'),
        ),
    ]
