# Generated by Django 3.0.4 on 2020-03-28 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_zero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('phone', models.CharField(max_length=120, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=120, null=True)),
                ('lat_lon', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_dropoff_only',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='lat_lon',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='zipcode',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.CreateModel(
            name='DonationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(max_length=120)),
                ('amount_requested', models.PositiveIntegerField()),
                ('amount_received', models.PositiveIntegerField(default=0)),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_zero.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=120, null=True)),
                ('item_type', models.CharField(max_length=120, null=True)),
                ('amount', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('donation_time', models.DateTimeField()),
                ('org_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_zero.Organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helper_zero.User')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='point_of_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helper_zero.User'),
        ),
    ]
