# Generated by Django 3.0.4 on 2020-03-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helper_zero', '0005_auto_20200328_0716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='long',
            new_name='lon',
        ),
    ]
