# Generated by Django 3.0.4 on 2020-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_zero', '0006_auto_20200328_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='lat_lon',
            new_name='lat',
        ),
        migrations.AddField(
            model_name='organization',
            name='lon',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
